export { default as Home } from './Home'
export { default as Browse } from './Browse'
export { default as Signin } from './Signin'
export { default as Signup } from './Signup'
export { default as Nomination } from './Nomination'
export { default as LeaderBoard} from './Leaderboard'
